project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute:
  freeze: auto

website:
  title: "Nick J Lyon"
  favicon: images/logo_lyon.png
  repo-url: https://github.com/njlyon0/njlyon0.github.io
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Code"
        href: code.qmd
      - text: "Teach"
        href: teach.qmd
      - text: "Write"
        href: write.qmd
      - text: "Consult"
        href: consult.qmd
    right:
      - text: "Tips & Tricks"
        href: https://njlyon0.github.io/teach_tutorials/
      - text: "Creative Projects"
        href: create.qmd
      - icon: github
        href: https://github.com/njlyon0/njlyon0.github.io
  page-footer:
    center: "Copyright &copy; 2026, Nicholas J Lyon"
    background: secondary

format:
  html:
    theme:
      light: _extensions/njlyon0/lyon_theme/lyon_light.scss
      dark: _extensions/njlyon0/lyon_theme/lyon_dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    code-annotations: hover
