---
title: "Research"
---

Other Collaborations (Post-Grad)
 
Green June Beetle Gut Communities
How do gut microbial communities in the green June beetle differ with gut region, life stage, and sex of adult beetle?
•	Kucuk, R.A., Campbell, B.J., Lyon, N.J., Caterino, M.S. Gut bacteria of adult and larval Cotinis nitida Linnaeus (Coleoptera: Scarabaeidae) demonstrate community differences according to life stage and gut region. [In prep]
 
 
Iowa Research (M.Sc.)
This research was conducted in the Ecology and Evolutionary Biology Program at Iowa State University and was co-advised by Dr. Diane Debinski (Montana State University) and Dr. Haldre Rogers (Iowa State University).
 
Motivating Questions
How can we best manage for speciose and diverse communities of insect pollinators and floral resources on agricultural lands? What are the differences between short-term community response and the response of pollinator taxa to continuous long-term (i.e., decades) management? What effect does varying landscape context have on within-site management for native bees? How might we account for climate change in developing restoration strategy?
 
Photo Gallery
For a set of some of the best (in my opinion) photos from my field seasons (2016-2018) click here.
 
Publications
•	Lyon, N.J., Debinski, D.M., Rogers, H.S., Adams, D.C., and Wilsey, B.J. An Integrated Approach to Restoring Grassland Function to Working Lands. Master of Science Thesis. (PDF)
o	Lyon, N.J., Debinski, D.M., Rogers, H.S. Plant and Pollinator Communities Responded Differently to Eleven Years of Management. [In prep]
o	Lyon, N.J., Debinski, D.M., Rangwala, I. Evaluating the Utility of Species Distribution Models in Informing Climate Change-Resilient Grassland Restoration Strategy. 7. Frontiers in Ecology and Evolution.
•	Coon, J.J., Lyon, N.J., Raynor, E.J., Debinski, D.M., Miller, J.R., Schact, W.H. 2021. Using Adaptive Management to Restore Grasslands Invaded by Tall Fescue (Schedonorus arundinaceus). 76. Rangeland Ecology and Management.
•	Lyon, N.J., Stein, D.S., Debinski, D.M., Miller, J.R., Schact, W.H. 2021. Responses of Flowering Plant and Butterfly Communities to Experimental Herbicide and Seeding Treatments for Native Grassland Restoration. 3. Ecological Restoration.
 
Presentations
•	Lyon, N.J. and Debinski, D.M. Evaluating the Effects of Eleven Years of Consistent Restoration Management. Ecological Society of America, Louisville KY, August 2019. Oral Presentation.
•	Lyon, N.J. Multivariate Statistics in R. Data Management and Analysis in R for Ecologists and Evolutionary Biologists (EEB 698), Ames IA, November 2018. Guest Lecture.
•	Lyon, N.J., Debinski, D.M., Miller, J., Schact, W. Native Plant and Pollinator Response to Management with Fire and Grazing. Ecological Society of America, New Orleans LA, August 2018. Oral Presentation.
•	Lyon, N.J., Debinski, D.M., Miller, J., Schact, W. Plant and Pollinator Response to Adaptive Management. Graduate and Professional Student Research Conference, Ames IA, April 2018. Awarded Best Oral Presentation.
•	Lyon, N.J., Debinski, D.M. Butterfly and Nectar-Producing Plant Response to Invasive Grass Management. Graduate Research in Ecology and Evolutionary Biology Symposium, Ames IA, February 2018
•	Lyon, N.J. An Integrated Approach to Tallgrass Prairie Restoration. Three-Minute Thesis, Ames IA, January 2018
•	Lyon, N. J., Debinski, D.M., and Rangwala, I. Species Distribution Modeling to Predict Prairie Restoration Success under Climate Change. Ecological Society of America, Portland OR, August 2017
•	Lyon, N.J. Predicted Response of Native Grassland Plants to Climate Change. Ten Years of Research in the Grand River Grasslands Symposium, Lamoni IA, June 2017
•	Lyon, N.J., Debinski, D.M., Miller, J., Schact, W., and Stein, D. Grazing, Burning, and Butterflies. Iowa Urban Tree Council, Des Moines IA, April 2017
•	Lyon, N.J., Debinski, D.M., Miller, J., Schact, W. and Stein, D. Adaptive Management for Prairie Plants and Pollinators in Midwestern Working Landscapes. Iowa Invasive Species Conference, Moravia IA, March 2017
•	Lyon, N.J. Incorporating Correlative Modeling into Modifying Restoration Strategies for the Future. Graduate Research in Ecology and Evolutionary Biology Symposium, Ames IA, February 2017
 
Washington Research (B.Sc.)
This research was conducted at the University of Puget Sound with Dr. Peter Hodum.
Motivating Questions
Do marine filter feeders ingest measurable quantities of microplastics? At what spatial scale can filter feeders be used as bioindicators of marine plastic contamination? Do sessile filter feeders ingest different amounts of plastic based on their relative tidal heights?
 
Publications
•	Lyon, N.J. and Hodum, P. 2015. Mytilus Mussels as Bio-indicators of Regional Microplastic Trends. University of Puget Sound Undergraduate Thesis.
 
Presentations
•	Lyon, N. Mytilus Mussels as Bio-indicators of Microplastic Pollution. Oral presentation. Air and Waste Management Student Challenge, Portland OR, April 2016. Awarded Best Presentation
•	Lyon, N. Mytilus Mussels as Bio-indicators of Microplastic Pollution. Oral presentation. Phi Sigma Research Symposium, University of Puget Sound, April 2016
•	Lyon, N. Mytilus Mussels as Bio-indicators of Microplastic Pollution. Oral presentation. Murdock College Science Research Conference, Vancouver WA (Hilton Vancouver), November 2015.
•	Lyon N. Mussels as Samplers of Regional Microplastic Contamination Trends. Poster presentation. Puget Sound Fall Research Symposium, University of Puget Sound, September 2015.
•	Lyon, N. Patterns of Microplastic Ingestion in Mytilus Mussels around Puget Sound, Washington. Oral presentation. Phi Sigma Research Symposium, University of Puget Sound, April 2015.
•	Lyon N. Patterns of Microplastic Ingestion in Mytilus Mussels around Puget Sound, Washington. Poster presentation. Puget Sound Fall Research Symposium, University of Puget Sound, September 2014.
•	Lyon, N. Plastic Contamination in Marine Environments. Oral presentation. Honors Research Symposium, Seattle University, October 2014.
