---
title: "Teaching"
---

# Test

## 2
### 3
#### 4
##### 5
###### 6



I am driven to be the kind of instructor who combines honest care for students with effective teaching practices and critical self-reflection to improve because those are the types of faculty that had the largest positive impact on my personal and professional lives. I have found that being this type of teacher is often synonymous with being a mentor and it is this role that I find especially attractive in pursuing a career in academia. Whether students are taking my classes because this particular subject is their passion or simply satisfying a non-major requirement, my philosophy is to teach from a place of empathy with the lives and struggles of the students in my classes, and this style of teaching is often conducive to forming mentor-mentee relationships with many students. I have been able to live out this philosophy with undergraduate students both in formal classroom contexts and in less structured field season and independent research contexts.
I have served as a teaching assistant (TA) for several classes including an upper level (i.e., junior & senior) ecology course and two introductory general biology courses (open to all grades). My teaching emphasizes transparency with students, constructive and thorough feedback, and frequent requests for (anonymized) student feedback on how my teaching could better serve them. I believe that students thrive (both personally and professionally) when the intended learning objectives of every assignment and lecture is communicated in a clear and concise way early and often. Students then understand what concept I am pushing them to grapple with in an assignment rather than becoming overly focused on the point value of said task. My open-door policy for student feedback also makes students feel listened to and welcome as colleagues into the classrooms I instruct and frequently their feedback improves my teaching in ways I would never have thought of alone. Here is an example of the kind of PowerPoints I create to discussion and engagement.
I also leap at the opportunity to guest lecture for courses whenever possible. So far the bulk of my experience with that type of teaching has been in the form of guest lectures on the statistical software R. This program has become increasingly widely used in published literature and is regarded as a valuable skill for graduate school so singular guest lectures on facets of R relevant to a particular course, unit, or project are useful. Provided below is a list of the guest lectures I have given to date and I am happy to share the materials I have created for these courses so just contact me if you’re interested!
Clemson University, Clemson SC
•	2020 – Introduction to Statistics and R in Ecology Research. Insect Ecology (ENT 4520/6520)
Iowa State University, Ames IA
•	2019 – Plotting with ggplot2. Data Wrangling in R for Natural Resource Professionals (NREM 305)
•	2019 – Choosing the “Right” Statistical Test. Data Wrangling in R for Natural Resource Professionals (NREM 305)
•	2018 – Multivariate Statistics in R. Data Management and Analysis in R for Ecologists and Evolutionary Biologists (EEB 698)
