{
  "hash": "3dc63be79efc54bcd23fdf5ffce301d4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Class Coercion (in R)\"\n---\n\n\n\n\nThe R programming language is extremely useful for a variety of data science tasks. It--and other object-oriented programming languages--allow storing values in \"objects\" and then using those objects to re-call and use the values to which they are bound. In order to combine different \"types\" of values, R has to \"coerce\" one or both of the values into a shared type (sometimes a.k.a. \"class\" depending on what you're working on).\n\n## Coercion Rules\n\n**The order of this coercion is `logical -> integer -> double -> character`**. Logicals are the most specific type of atomic vector and the order proceeds to characters which are the most general type. It might be helpful to consider some examples. Let's begin by making one object for each atomic type (identified above).\n\n:::{.panel-tabset}\n#### Logical\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_logi <- c(TRUE, FALSE)\ntypeof(x = my_logi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"logical\"\n```\n\n\n:::\n:::\n\n\n\n\n#### Integer\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_int <- c(4L, 5L, 6L) # <1>\ntypeof(x = my_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"integer\"\n```\n\n\n:::\n:::\n\n\n\n1. The `L` at the end is for \"length\" and ensures that number is type \n\n#### Double\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_doub <- c(3.14, 77.0, 20) # <2>\ntypeof(x = my_doub)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"double\"\n```\n\n\n:::\n:::\n\n\n\n2. Even though \"20\" _looks_ like an integer, R will consider it a double without the trailing `L`\n\n#### Character\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_char <- c(\"a\", \"b\", \"c\")\ntypeof(x = my_char)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\nNow that we have those, let's combine them in sequence so we can see the coercion rules in action!\n\n:::{.panel-tabset}\n#### Logical + Integer\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_logi.int <- c(my_logi, my_int)\nmy_logi.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 0 4 5 6\n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(x = my_logi.int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"integer\"\n```\n\n\n:::\n:::\n\n\n\n\n#### Integer + Double\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_int.doub <- c(my_int, my_doub)\nmy_int.doub\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  4.00  5.00  6.00  3.14 77.00 20.00\n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(x = my_int.doub)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"double\"\n```\n\n\n:::\n:::\n\n\n\n\n#### Double + Character\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_doub.char <- c(my_doub, my_char)\nmy_doub.char\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"3.14\" \"77\"   \"20\"   \"a\"    \"b\"    \"c\"   \n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(x = my_doub.char)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n\n\n:::\n\n### Other Coercion Variants\n\nYou may have noticed that the above examples are missing some classes of object with which you may work regularly. These were absent from the above examples because the first component of this tip is restricted only to \"type\" coercion while you may be thinking of \"class\" coercion. See below for some examples that may address what felt missing above.\n\n:::{.panel-tabset}\n#### Numeric Coercion\n\n<u>\"Numeric\" values are technically inclusive of both integers and doubles</u>. The reason to avoid that phrasing earlier was just to be more precise about the coercion rules between integers and doubles.\n\n#### Factor Coercion\n\n<u>Factors are a special case of an integer</u>. This does mean that coercing a factor can have surprising results in some cases.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make our character object into a factor\nmy_fact <- as.factor(x = my_char)\nmy_fact\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] a b c\nLevels: a b c\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check the type & class\ntypeof(x = my_fact)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"integer\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(x = my_fact)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"factor\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Coerce it by combining with a double\nmy_doub.fact <- c(my_doub, my_fact)\nmy_doub.fact # <3>\ntypeof(x = my_doub.fact)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  3.14 77.00 20.00  1.00  2.00  3.00\n[1] \"double\"\n```\n\n\n:::\n:::\n\n\n\n3. Because doubles \"win\" coercion against integers, our `a`, `b`, and `c` become `1.00`, `2.00`, and `3.00` respectively!\n\n#### Date Coercion\n\n<u>Dates are a special case of a double</u>. They represent the number of **days** since January 1^st^, 1970. Like factors, this means that coercion can behave in a way that surprises you.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a date\nmy_date <- as.Date(x = \"2024-10-13\")\n\n# Check the type & class\ntypeof(x = my_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"double\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(x = my_date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Coerce it by combining with a character\nmy_char.date <- c(my_char, my_date)\nmy_char.date\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"a\"     \"b\"     \"c\"     \"20009\"\n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(x = my_char.date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n\n\n#### Date-Time Coercion\n\n<u>Date-times are a special case of a double</u>. They represent the number of **seconds** since January 1^st^, 1970. Just like dates, this can make coercion surprising here as well.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a datetime\nmy_datetime <- as.POSIXct(\"2024-10-13 23:00\", tz = \"UTC\")\n\n# Check the type & class\ntypeof(x = my_datetime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"double\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(x = my_datetime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"POSIXct\" \"POSIXt\" \n```\n\n\n:::\n\n```{.r .cell-code}\n# Coerce it by combining with a character\nmy_char.datetime <- c(my_char, my_datetime)\nmy_char.datetime\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"a\"          \"b\"          \"c\"          \"1728860400\"\n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(x = my_char.datetime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n\n\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}